### ISSUE TITLE
an update required

### ISSUE THREAD

**Issue by whelks-chance** [jakobadam/bootstrap-uploadprogress#3]
Error:
ModelForm without 'fields' or the 'exclude' attribute is deprecated

is given with latest Django. 

```
exclude = []
```

needed in PackageForm's Meta class.

class PackageForm(forms.ModelForm):

```
class Meta:
    exclude = []
    model = Package
    widgets = {
        'name': _get_widget('Enter package name')
        }
```

**Comment by jakobadam** [comment]
Thanks for reporting.
